language: objective-c  #1

before_install:
   - rvm use system
   - sudo gem install cocoapods -v '0.39.0'

osx_image: xcode10.1 #2
xcode_workspace: ITISService.xcworkspace #3
xcode_scheme: ITISService Production #4
xcode_sdk: iphonesimulator12.1 #5