//
//  SettingsPresenter.swift
//  ITISService
//
//  Created by Timur Shafigullin on 05/12/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsPresentationLogic {
    func displaySettings(with response: Settings.InitialState.Response)
}

class SettingsPresenter: SettingsPresentationLogic {
    
    // MARK: - Instance Properties
    
    weak var viewController: SettingsDisplayLogic!

    // MARK: - Instance Methods
    
    func displaySettings(with response: Settings.InitialState.Response) {
        let items = response.settingsNames.map {
            return Settings.TableView.Model(settingName: $0)
        }
        
        let section = DefaultTableViewSection(items: items, headerTitle: "Основные")
        
        self.viewController.displaySettingRows(with: [section])
    }
    
}
