//
//  SettingsInteractor.swift
//  ITISService
//
//  Created by Timur Shafigullin on 05/12/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsBusinessLogic {
    func prepareInitialState()
}

protocol SettingsDataStore {
    
}

class SettingsInteractor: SettingsBusinessLogic, SettingsDataStore {
    
    // MARK: - Instance Properties
    
    var presenter: SettingsPresentationLogic!
    var worker: SettingsWorker!
    
    // MARK: -
    
    fileprivate var settingNames = ["Аккаунт", "Уведомления", "Опрос"]
    
    // MARK: - Instance Methods
    
    func prepareInitialState() {
        self.presenter.displaySettings(with: Settings.InitialState.Response(settingsNames: self.settingNames))
        
        if let user = Managers.userManager.first() {
            self.presenter.displayUserInfo(with: Settings.UserProfile.Response(user: user))
        }
    }
}
