//
//  SettingsInteractor.swift
//  ITISService
//
//  Created by Timur Shafigullin on 05/12/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsBusinessLogic {
    func prepareInitialState()
    func selectCellRequest(with request: Settings.SelectCell.Request)
    func exitProfile()
    
    func subscribeToSignInNotification()
    func subscribeToSignUpNotification()
}

protocol SettingsDataStore {
    
}

class SettingsInteractor: SettingsBusinessLogic, SettingsDataStore {
    
    // MARK: - Nested Types
    
    fileprivate enum Constants {
        
        // MARK: - Type Properties
        
        static let mainSectionIndex = 0
        
        static let exitRowIndex = 3
    }
    
    // MARK: - Instance Properties
    
    var presenter: SettingsPresentationLogic!
    var worker: SettingsWorker!
    
    // MARK: -
    
    fileprivate var settingNames = ["Аккаунт", "Уведомления", "Опрос"]
    fileprivate var signInObserver: AnyObject?
    fileprivate var signUpObserver: AnyObject?
    
    // MARK: - Initializers
    
    deinit {
        self.unsubscribeFromSignInNotification()
        self.unsubscribeFromSignUpNotification()
    }
    
    // MARK: - Instance Methods
    
    fileprivate func unsubscribeFromSignInNotification() {
        if let signInObserver = self.signInObserver {
            NotificationCenter.default.removeObserver(signInObserver)
            self.signInObserver = nil
        }
    }
    
    fileprivate func unsubscribeFromSignUpNotification() {
        if let signUpObserver = self.signUpObserver {
            NotificationCenter.default.removeObserver(signUpObserver)
            self.signUpObserver = nil
        }
    }
    
    // MARK: -
    
    func prepareInitialState() {
        self.presenter.displaySettings(with: Settings.InitialState.Response(settingsNames: self.settingNames))
        
        if let user = Managers.userManager.first() {
            self.presenter.displayUserInfo(with: Settings.UserProfile.Response(user: user))
        }
    }
    
    // MARK: -
    
    func selectCellRequest(with request: Settings.SelectCell.Request) {
        let indexPath = request.indexPath
        
        if indexPath.section == Constants.mainSectionIndex {
            if indexPath.row == Constants.exitRowIndex {
                self.presenter.displayConfirmExitActionSheet()
            }
        }
    }
    
    func exitProfile() {
        Managers.userManager.deleteAll()
        KeychainManager.shared.clear()
        
        self.presenter.showLoginScreen()
    }
    
    // MARK: -
    
    func subscribeToSignInNotification() {
        self.signInObserver = NotificationCenter.default.addObserver(forName: .userDidSignIn, object: nil, queue: OperationQueue.main) { [weak self] (notification) in
            if let user = Managers.userManager.first() {
                self?.presenter.displayUserInfo(with: Settings.UserProfile.Response(user: user))
            }
        }
    }
    
    func subscribeToSignUpNotification() {
        self.signUpObserver = NotificationCenter.default.addObserver(forName: .userDidSignUp, object: nil, queue: OperationQueue.main, using: { [weak self] (notification) in
            if let user = Managers.userManager.first() {
                self?.presenter.displayUserInfo(with: Settings.UserProfile.Response(user: user))
            }
        })
    }
}
