//
//  RegistrationPresenter.swift
//  ITISService
//
//  Created by Тимур Шафигуллин on 22/10/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistrationPresentationLogic {
    func presentSomething(response: Registration.Something.Response)
}

class RegistrationPresenter: RegistrationPresentationLogic {
    
    weak var viewController: RegistrationDisplayLogic?

    // MARK: Do something

    func presentSomething(response: Registration.Something.Response) {
        let viewModel = Registration.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
