//
//  RegistrationPresenter.swift
//  ITISService
//
//  Created by Тимур Шафигуллин on 22/10/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistrationPresentationLogic {
    func signUp(response: Registration.SignUp.Response)
}

class RegistrationPresenter: RegistrationPresentationLogic {
    
    weak var viewController: RegistrationDisplayLogic!
    
    func signUp(response: Registration.SignUp.Response) {
        if (response.success) {
            self.viewController.showCourses()
        } else {
            let viewModel = Registration.SignUp.ViewModel(
                errorMessage: response.message!,
                emailTextColor: response.errorType == .email ? Common.Autorization.errorColor : .white,
                passwordsTextColor: response.errorType == .password ? Common.Autorization.errorColor : .white)
            self.viewController.showError(with: viewModel)
        }
    }
    
}
