//
//  RegistrationInteractor.swift
//  ITISService
//
//  Created by Тимур Шафигуллин on 22/10/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistrationBusinessLogic {
    func doSomething(request: Registration.Something.Request)
}

protocol RegistrationDataStore {
    //var name: String { get set }
}

class RegistrationInteractor: RegistrationBusinessLogic, RegistrationDataStore {
    
    var presenter: RegistrationPresentationLogic?
    var worker: RegistrationWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: Registration.Something.Request) {
        worker = RegistrationWorker()
        worker?.doSomeWork()

        let response = Registration.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
