//
//  CoursesInteractor.swift
//  ITISService
//
//  Created by Тимур Шафигуллин on 27/10/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CoursesBusinessLogic {
    func doSomething(request: Courses.Something.Request)
}

protocol CoursesDataStore {
    //var name: String { get set }
}

class CoursesInteractor: CoursesBusinessLogic, CoursesDataStore {
    
    var presenter: CoursesPresentationLogic?
    var worker: CoursesWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: Courses.Something.Request) {
        worker = CoursesWorker()
        worker?.doSomeWork()

        let response = Courses.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
