//
//  CoursesInteractor.swift
//  ITISService
//
//  Created by Тимур Шафигуллин on 27/10/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CoursesBusinessLogic {
    func fetchCourses()
    func selectCourse(at indexPath: IndexPath, numberOfSections: Int)
    
    func subscribeToUserUnauthorizedNotification()
    func subsribeToUserSignInNotification()
    func subscribeToUserFinishQuizNotification()
    func subsribeToUserSignUpNotification()
}

protocol CoursesDataStore {
    var listCourses: ListCourses? { get }
    var selectedCourse: Course? { get }
    
    func updateListCourses()
}

class CoursesInteractor: CoursesBusinessLogic, CoursesDataStore {
    
    // MARK: - Nested Types
    
    fileprivate struct Constants {
        
        // MARK: - Properties
        
        static let suggestedCoursesSectionIndex = 0
        static let allCoursesSectionIndex = 1
    }
    
    // MARK: - Instance Properties
    
    fileprivate var userUnauthorizedObserver: AnyObject?
    fileprivate var userSignInObserver: AnyObject?
    fileprivate var userFinishQuizObserver: AnyObject?
    fileprivate var userSignUpObserver: AnyObject?
    
    // MARK: -
    
    var presenter: CoursesPresentationLogic!
    var worker: CoursesWorker!
    var userNetworkManager: UserNetworkManager!
    
    var listCourses: ListCourses?
    var selectedCourse: Course?
    
    // MARK: - Initializers
    
    deinit {
        self.unsubscribeFromUserUnauthorizedNotification()
        self.unsubscribeFromUserSignInNotification()
        self.unsubscribeFromUserFinishQuiz()
        self.unsubscriveFromUserSignUpNotification()
    }

    // MARK: - Instance Methods
    
    fileprivate func unsubscribeFromUserUnauthorizedNotification() {
        if let userUnauthorizedObserver = self.userUnauthorizedObserver {
            NotificationCenter.default.removeObserver(userUnauthorizedObserver)
            self.userUnauthorizedObserver = nil
        }
    }
    
    fileprivate func unsubscribeFromUserSignInNotification() {
        if let userSignInObserver = self.userSignInObserver {
            NotificationCenter.default.removeObserver(userSignInObserver)
            self.userSignInObserver = nil
        }
    }
    
    fileprivate func unsubscribeFromUserFinishQuiz() {
        if let userFinishQuizObserver = self.userFinishQuizObserver {
            NotificationCenter.default.removeObserver(userFinishQuizObserver)
            self.userFinishQuizObserver = nil
        }
    }
    
    fileprivate func unsubscriveFromUserSignUpNotification() {
        if let userSignUpObserver = self.userSignUpObserver {
            NotificationCenter.default.removeObserver(userSignUpObserver)
            self.userSignUpObserver = nil
        }
    }
    
    // MARK: -
    
    func updateListCourses() {
        self.fetchCourses()
    }
    
    func fetchCourses() {
        guard Managers.userManager.first() != nil else {
            return
        }
        
        self.presenter.showActivityIndicator(true)
        self.userNetworkManager.fetchCourses(success: { [weak self] (listCourses) in
            guard let strongSelf = self else {
                return
            }
            
            strongSelf.presenter.showActivityIndicator(false)
            strongSelf.listCourses = listCourses
            strongSelf.presenter.displayCourses(response: Courses.List.Response(listCourses: listCourses))
        }) { [weak self] (error) in
            self?.presenter.showActivityIndicator(false)
            self?.presenter.showAlert(with: error)
        }
    }
    
    // MARK: -
    
    func selectCourse(at indexPath: IndexPath, numberOfSections: Int) {
        guard let listCourses = self.listCourses else {
            return
        }
        
        var sections = [[Course]]()
        
        if !listCourses.userCourses.isEmpty {
            sections.append(listCourses.userCourses)
        }
        
        if !listCourses.suggestedCourses.isEmpty {
            sections.append(listCourses.suggestedCourses)
        }
        
        if !listCourses.allCourses.isEmpty {
            sections.append(listCourses.allCourses)
        }
        
        self.selectedCourse = sections[indexPath.section][indexPath.row]
    }
    
    // MARK: -
    
    func subscribeToUserUnauthorizedNotification() {
        self.userUnauthorizedObserver = NotificationCenter.default.addObserver(forName: .userUnauthorized, object: nil, queue: OperationQueue.main, using: { [weak self] (notification) in
            self?.presenter.showLoginScreen()
        })
    }
    
    func subsribeToUserSignInNotification() {
        self.userSignInObserver = NotificationCenter.default.addObserver(forName: .userDidSignIn, object: nil, queue: OperationQueue.main, using: { [weak self] (notification) in
            self?.fetchCourses()
        })
    }
    
    func subscribeToUserFinishQuizNotification() {
        self.userFinishQuizObserver = NotificationCenter.default.addObserver(forName: .userDidFinishQuiz, object: nil, queue: OperationQueue.main, using: { [weak self] (notification) in
            self?.fetchCourses()
        })
    }
    
    func subsribeToUserSignUpNotification() {
        self.userSignUpObserver = NotificationCenter.default.addObserver(forName: .userDidSignUp, object: nil, queue: OperationQueue.main, using: { [weak self] (notification) in
            self?.fetchCourses()
        })
    }
}
