//
//  CoursesModels.swift
//  ITISService
//
//  Created by Тимур Шафигуллин on 27/10/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Courses {
    
    // MARK: - Use cases
  
    enum List {
        struct Request {
            
        }
        struct Response {
            let listCourses: ListCourses
        }
        struct ViewModel {
            
        }
    }
    
    enum CourseStatus {
        struct Request {
            
        }
        struct Response {
            let courseID: Int
        }
        struct ViewModel {
            
        }
    }
    
    enum Points {
        struct Request {
            
        }
        struct Response {
            let courseID: Int
        }
        struct ViewModel {
            
        }
    }
    
    // MARK: - TableView Models
    
    enum TableView {
        
        struct Model: TableViewCompatible {
            
            var reuseIdentifier: String {
                return CourseTableViewCell.identifier()
            }
            
            let name: String
            let description: String
            
            func cell(for tableView: UITableView, at indexPath: IndexPath) -> UITableViewCell {
                let cell = tableView.dequeueReusableCell(withIdentifier: self.reuseIdentifier, for: indexPath) as! CourseTableViewCell
                cell.configure(with: self)
                return cell
            }
        }
        
        struct Section: TableViewSection {
            
            var items: [TableViewCompatible]
            var headerTitle: String?
            var footerTitle: String?
            
            init(items: [TableViewCompatible], headerTitle: String?, footerTitle: String? = nil) {
                self.items = items
                self.headerTitle = headerTitle
                self.footerTitle = footerTitle
            }
        }
    }
    
}
