//
//  CoursesViewController.swift
//  ITISService
//
//  Created by Тимур Шафигуллин on 27/10/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CoursesDisplayLogic: LoaderDisplayLogic, ErrorMessagePresenter {
    func displayListCourses(sections: [Courses.TableView.Section])
}

class CoursesViewController: UIViewController, CoursesDisplayLogic {
    
    // MARK: - Constants
    
    fileprivate struct Constants {
        static let backgroundColor = UIColor(red: 42 / 255.0, green: 42 / 255.0, blue: 42 / 255.0, alpha: 1)
    }
    
    // MARK: - Instance Properties
    
    @IBOutlet weak var tableView: UITableView!
    
    // MARK: -
    
    private let datasource = CoursesDatasource()
    
    var interactor: CoursesBusinessLogic!
    var router: (NSObjectProtocol & CoursesRoutingLogic & CoursesDataPassing)!
    
    // MARK: - Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: - Setup
    
    private func setup() {
        let viewController = self
        let interactor = CoursesInteractor()
        let presenter = CoursesPresenter()
        let router = CoursesRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        interactor.userNetworkManager = NetworkManagers.userNetworkManager
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: - Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: - Instance Methods
    
    // MARK: -
    
    private func configureDesign() {
        self.navigationController?.navigationBar.titleTextAttributes = [
            .foregroundColor: UIColor.white,
            .font: UIFont(name: "HelveticaNeue-Light", size: 17)!
        ]
        self.navigationController?.navigationBar.barTintColor = Constants.backgroundColor
        
        self.tableView.register(CourseTableViewCell.nib(), forCellReuseIdentifier: CourseTableViewCell.identifier())
        self.tableView.dataSource = self.datasource
        self.tableView.delegate = self.datasource
        
        self.datasource.onTap = { (indexPath) in
            //Open course details screen
        }
    }
    
    // MARK: - UIViewController
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.configureDesign()
        self.interactor.fetchCourses()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }
    
    // MARK: - CoursesDisplayLogic Methods
    
    func displayListCourses(sections: [Courses.TableView.Section]) {
        self.datasource.sections = sections
        self.tableView.reloadData()
    }
    
}
