//
//  CoursesPresenter.swift
//  ITISService
//
//  Created by Тимур Шафигуллин on 27/10/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CoursesPresentationLogic: LoaderPresentationLogic, ErrorMessagePrentationLogic {
    func displayCourses(response: Courses.List.Response)
    func showLoginScreen()
    func didCourseDetailsStatusChanged(with response: Courses.CourseStatus.Response)
}

class CoursesPresenter: CoursesPresentationLogic {
    
    // MARK: - Instance Properties
    
    weak var viewController: CoursesDisplayLogic!
    
    weak var loaderDislpayViewController: LoaderDisplayLogic! {
        get {
            return self.viewController
        }
    }
    
    weak var errorMessagePresenter: ErrorMessagePresenter! {
        get {
            return self.viewController
        }
    }

    // MARK: - Instance Methods
    
    func displayCourses(response: Courses.List.Response) {
        let userCourses = response.listCourses.userCourses.map {
            return Courses.TableView.Model(name: $0.name, description: $0.description)
        }
        
        let suggestedCourses = response.listCourses.suggestedCourses.map {
            return Courses.TableView.Model(name: $0.name, description: $0.description)
        }
        
        let allCourses = response.listCourses.allCourses.map {
            return Courses.TableView.Model(name: $0.name, description: $0.description)
        }
        
        var sections = [Courses.TableView.Section]()
        
        if !userCourses.isEmpty {
            let userCoursesSection = Courses.TableView.Section(items: userCourses, headerTitle: "Мои курсы")
            sections.append(userCoursesSection)
        }
        
        if !suggestedCourses.isEmpty {
            let suggestedCoursesSection = Courses.TableView.Section(items: suggestedCourses, headerTitle: "Предложенные курсы")
            sections.append(suggestedCoursesSection)
        }
        
        if !allCourses.isEmpty {
            let allCoursesSection = Courses.TableView.Section(items: allCourses, headerTitle: "Все курсы")
            sections.append(allCoursesSection)
        }
        
        self.viewController.displayListCourses(sections: sections)
    }
    
    func showLoginScreen() {
        self.viewController.showLoginScreen()
    }
    
    func didCourseDetailsStatusChanged(with response: Courses.CourseStatus.Response) {
        self.viewController.showCourseDetailsScreen(with: response.courseID)
    }
}
