//
//  CoursesRouter.swift
//  ITISService
//
//  Created by Тимур Шафигуллин on 27/10/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CoursesRoutingLogic {
    func routeToCourseDetails(segue: UIStoryboardSegue)
}

protocol CoursesDataPassing {
    var dataStore: CoursesDataStore! { get }
}

class CoursesRouter: NSObject, CoursesRoutingLogic, CoursesDataPassing {
    
    // MARK: - Instance Properties
    
    weak var viewController: CoursesViewController!
    var dataStore: CoursesDataStore!
    
    // MARK: - Instance Methods
    
    fileprivate func passDataToCourseDetails(source: CoursesDataStore, destination: CourseDetailsDataStore) {
        if let course = source.selectedCourse {
            destination.course = course
        }
    }
    
    // MARK: -
    
    func routeToCourseDetails(segue: UIStoryboardSegue) {
        guard let datasourceHolder = segue.destination as? CourseDetailsDataStoreHolder else {
            return
        }
        
        self.passDataToCourseDetails(source: self.dataStore, destination: datasourceHolder.courseDetailsDataStore)
    }
}
