//
//  PointsInteractor.swift
//  ITISService
//
//  Created by Timur Shafigullin on 02/12/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PointsBusinessLogic {
    func fetchPoints()
}

protocol PointsDataStore: class {
    var course: Course! { get set }
}

class PointsInteractor: PointsBusinessLogic, PointsDataStore {
    
    // MARK: - Instance Properties
    
    var presenter: PointsPresentationLogic!
    var worker: PointsWorker!
    var userNetworkManager: UserNetworkManager!
    
    // MARK: -
    
    var course: Course!

    // MARK - Instance Methods

    func fetchPoints() {
        self.presenter.showActivityIndicator(true)
        
        self.userNetworkManager.fetchPoints(courseID: self.course.id, success: { [weak self] (userPoints) in
            self?.presenter.showActivityIndicator(false)
            self?.presenter.displayPoints(with: Points.Fetch.Response(total: userPoints.total, points: userPoints.points))
        }) { [weak self] (error) in
            self?.presenter.showActivityIndicator(false)
            self?.presenter.showAlert(with: error)
        }
    }
    
}
