//
//  PointsPresenter.swift
//  ITISService
//
//  Created by Timur Shafigullin on 02/12/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PointsPresentationLogic: LoaderPresentationLogic, ErrorMessagePrentationLogic {
    func displayPoints(with response: Points.Fetch.Response)
}

class PointsPresenter: PointsPresentationLogic {
    
    // MARK: - Instance Properties
    
    weak var viewController: PointsDisplayLogic?
    
    weak var loaderDislpayViewController: LoaderDisplayLogic! {
        return self.viewController
    }
    
    weak var errorMessagePresenter: ErrorMessagePresenter! {
        return self.viewController
    }
    
    // MARK: - Instance Methods
    
    func displayPoints(with response: Points.Fetch.Response) {
        let totalCount = response.total > 0 ? "+\(response.total)" : "\(response.total)"
        let points = response.points
        
        let tableViewItems = points.map {
            return Points.TableView.Model(title: $0.title, description: $0.description, count: $0.count)
        }
        
        let section = DefaultTableViewSection(items: tableViewItems)
        
        self.viewController?.showPoints(sections: [section], viewModel: Points.Fetch.ViewModel(totalCount: totalCount))
    }
}
