//
//  NotificationSettingsModels.swift
//  ITISService
//
//  Created by Timur Shafigullin on 19/12/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NotificationSettings {
  // MARK: Use cases
  
    enum InitialState {
        struct Request {
            
        }
        struct Response {
            let sections: [TableViewSection]
        }
        struct ViewModel {
            
        }
    }
    
    enum TableView {
        struct Model: TableViewCompatible {
            
            let title: String
            let isOn: Bool
            
            var onSwitchValueChanged: ((Bool) -> Void)?
            
            var reuseIdentifier: String {
                return NotificationSettingTableViewCell.identifier()
            }
            
            func cell(for tableView: UITableView, at indexPath: IndexPath) -> UITableViewCell {
                let cell = tableView.dequeueReusableCell(withIdentifier: reuseIdentifier, for: indexPath) as! NotificationSettingTableViewCell
                
                cell.configure(with: self)
                return cell
            }
        }
    }
    
}
