//
//  NotificationSettingsPresenter.swift
//  ITISService
//
//  Created by Timur Shafigullin on 19/12/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotificationSettingsPresentationLogic {
    func didInitialStateSetuped(with response: NotificationSettings.InitialState.Response) 
}

class NotificationSettingsPresenter: NotificationSettingsPresentationLogic {
    
    // MARK: - Instance Properties
    
    weak var viewController: NotificationSettingsDisplayLogic!

    // MARK: - Instance Methods
    
    func didInitialStateSetuped(with response: NotificationSettings.InitialState.Response) {
        self.viewController.showNotificationSettings(with: response.sections)
    }
    
}
