//
//  NotificationSettingsInteractor.swift
//  ITISService
//
//  Created by Timur Shafigullin on 19/12/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotificationSettingsBusinessLogic {
    func setupInitialState()
}

protocol NotificationSettingsDataStore {
   
}

class NotificationSettingsInteractor: NotificationSettingsBusinessLogic, NotificationSettingsDataStore {
    
    // MARK: - Instance Properties
    
    var presenter: NotificationSettingsPresentationLogic!
    var worker: NotificationSettingsWorker!
    
    // MARK: - Instance Methods
    
    func setupInitialState() {
        let courseStatus = NotificationSettings.TableView.Model(title: "Статус курса", onSwitchValueChanged: { [unowned self] (isOn) in
            // TODO: - Send action to server
        })
        
        let points = NotificationSettings.TableView.Model(title: "Баллы") { [unowned self] (isOn) in
            // TODO: - Send action to server
        }
        
        let mainSection = DefaultTableViewSection(items: [courseStatus, points], headerTitle: "Основные")
        
        let response = NotificationSettings.InitialState.Response(sections: [mainSection])
        
        self.presenter.didInitialStateSetuped(with: response)
    }
    
}
