//
//  CourseDetailsRouter.swift
//  ITISService
//
//  Created by Timur Shafigullin on 25/11/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CourseDetailsRoutingLogic {
    func routeToUserPoints(segue: UIStoryboardSegue)
    func updateListCourse()
}

protocol CourseDetailsDataPassing {
    var dataStore: CourseDetailsDataStore! { get }
}

class CourseDetailsRouter: NSObject, CourseDetailsRoutingLogic, CourseDetailsDataPassing {
    
    // MARK: - Instance Properties
    
    weak var viewController: CourseDetailsViewController!
    var dataStore: CourseDetailsDataStore!
    
    // MARK: - Instance Methods

    func routeToUserPoints(segue: UIStoryboardSegue) {
        guard let dataStoreHolder = segue.destination as? PointsDataStoreHolder else {
            return
        }
        
        dataStoreHolder.datastore.userPoints = dataStore.courseDetails?.userPoints
        dataStoreHolder.datastore.courseID = dataStore.course?.id
    }
    
    func updateListCourse() {
        guard let dataStoreHolder = viewController.navigationController?.viewControllers.first as? CoursesDataStoreHolder else {
            return
        }
        
        dataStoreHolder.dataStore.updateListCourses()
    }
    
}
