//
//  CourseDetailsModels.swift
//  ITISService
//
//  Created by Timur Shafigullin on 25/11/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CourseDetailsModels {
    
  // MARK: - Use cases
  
    enum InitialSate {
        struct Response {
            let course: Course
        }
        struct ViewModel {
            let name: String
            let description: String
        }
    }
    
    enum Fetch {
        struct Response {
            let courseDetails: CourseDetails
        }
        struct ViewModel {
            let times: String
            let place: String
            let teacherName: String
            let teacherLink: NSAttributedString
            let foregroundColor: UIColor
            let underlineStyle: NSUnderlineStyle
            let shouldShowManagementView: Bool
            let shouldShowAcademicPerformanceButton: Bool
            let shouldShowSignUpCourseButton: Bool
            let courseStatus: String?
        }
    }
    
}
