//
//  AccountSettingsPresenter.swift
//  ITISService
//
//  Created by Timur Shafigullin on 10/12/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountSettingsPresentationLogic: ErrorMessagePrentationLogic, LoaderPresentationLogic {
    func displayInitialAccountSettingsRows(with sections: [TableViewSection])
    func passwordDidUpdated()
    func passwordRowsDidChanged(with response: AccountSettings.DoneButton.Response)
}

class AccountSettingsPresenter: AccountSettingsPresentationLogic {
    
    // MARK: - Instance Properties
    
    weak var viewController: AccountSettingsDisplayLogic!
    
    var errorMessagePresenter: ErrorMessagePresenter! {
        return self.viewController
    }
    
    var loaderDislpayViewController: LoaderDisplayLogic! {
        return self.viewController
    }
    
    // MARK: - Instance Methods

    func displayInitialAccountSettingsRows(with sections: [TableViewSection]) {
        self.viewController.displayRows(with: sections)
    }
    
    func passwordRowsDidChanged(with response: AccountSettings.DoneButton.Response) {
        self.viewController.updateDoneButtonState(with: AccountSettings.DoneButton.ViewModel(doneButtonEnabled: !response.hasEmptyField))
    }
    
    func passwordDidUpdated() {
        self.viewController.closeAccountSettingsScreen()
    }
}
