//
//  AccountSettingsViewController.swift
//  ITISService
//
//  Created by Timur Shafigullin on 10/12/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountSettingsDisplayLogic: ErrorMessagePresenter, LoaderDisplayLogic {
    func displayRows(with sections: [TableViewSection])
    func updateDoneButtonState(with viewModel: AccountSettings.DoneButton.ViewModel)
    func closeAccountSettingsScreen()
}

class AccountSettingsViewController: UIViewController, AccountSettingsDisplayLogic {
    
    // MARK: - Instance Properties
    
    @IBOutlet fileprivate weak var tableView: UITableView!
    
    // MARK: -
    
    fileprivate let datasource = AccountSettingsDatasource()
    
    // MARK: -
    
    var interactor: AccountSettingsBusinessLogic!
    var router: (NSObjectProtocol & AccountSettingsRoutingLogic & AccountSettingsDataPassing)!
    
    // MARK: - Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: - Setup
    
    private func setup() {
        let viewController = self
        let interactor = AccountSettingsInteractor()
        let presenter = AccountSettingsPresenter()
        let router = AccountSettingsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        interactor.userNetworkManager = NetworkManagers.userNetworkManager
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: - Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: - Instance Methods
    
    @objc fileprivate func onDoneButtonTouchUpInside(_ sender: UIBarButtonItem) {
        self.interactor.changePassword()
    }
    
    // MARK: -
    
    private func configureDesign() {
        let doneBarButton = UIBarButtonItem(title: "Готово", style: .done, target: self, action: #selector(onDoneButtonTouchUpInside(_:)))
        
        doneBarButton.isEnabled = false
        
        self.navigationItem.rightBarButtonItem = doneBarButton
        
        self.tableView.dataSource = self.datasource
        self.tableView.delegate = self.datasource
        self.tableView.tableFooterView = UIView()
        self.tableView.register(TextFieldTableViewCell.nib(), forCellReuseIdentifier: TextFieldTableViewCell.identifier())
        
        self.interactor.prepareInitialState()
    }
    
    // MARK: - UIViewController
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.configureDesign()
    }
    
    // MARK: - AccountSettingsDisplayLogic Methods
    
    func displayRows(with sections: [TableViewSection]) {
        self.datasource.sections = sections
        self.tableView.reloadData()
    }
    
    func updateDoneButtonState(with viewModel: AccountSettings.DoneButton.ViewModel) {
        self.navigationItem.rightBarButtonItem?.isEnabled = viewModel.doneButtonEnabled
    }
    
    func closeAccountSettingsScreen() {
        self.navigationController?.popViewController(animated: true)
    }
}
