//
//  LoginRouter.swift
//  ITISService
//
//  Created by Тимур Шафигуллин on 19/10/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    func openCourseScreen()
    func openStartQuizScreen()
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore! { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    
    // MARK: - Nested Types
    
    fileprivate enum Segues {
        
        // MARK: - Type Properties
        
        static let finishLogin = "FinishLogin"
        static let showStartQuiz = "ShowStartQuiz"
    }
    
    // MARK: - Instance Properties
    
    weak var viewController: LoginViewController!
    var dataStore: LoginDataStore!
    
    // MARK: - Instance Methods
    
    func openCourseScreen() {
        self.viewController.performSegue(withIdentifier: Segues.finishLogin, sender: self.viewController)
    }
    
    func openStartQuizScreen() {
        self.viewController.performSegue(withIdentifier: Segues.showStartQuiz, sender: self.viewController)
    }
}
