//
//  LoginPresenter.swift
//  ITISService
//
//  Created by Тимур Шафигуллин on 19/10/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    
    func signIn(response: Login.SignIn.Response)
    
}

class LoginPresenter: LoginPresentationLogic {
    
    weak var viewController: LoginDisplayLogic!
    
    func signIn(response: Login.SignIn.Response) {
        if (response.success) {
            if (response.shouldShowQuiz) {
                viewController.openStartQuizScreen()
            } else {
                viewController.openCoursesScreen()
            }
        } else {
            let viewModel = Login.SignIn.ViewModel(errorMessage: response.message)
            viewController.showError(with: viewModel)
        }
    }
    
}
