//
//  LoginViewController.swift
//  ITISService
//
//  Created by Тимур Шафигуллин on 19/10/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: class {
    
    func openCoursesScreen()
    func showError(with viewModel: Login.SignIn.ViewModel)
    
}

class LoginViewController: UIViewController, LoginDisplayLogic {
    
    //MARK: - Constants
    
    fileprivate struct Constants {
        static let titleColor = UIColor(red: 153 / 255.0, green: 153 / 255.0, blue: 149 / 255.0, alpha: 1)
    }
    
    //MARK: - Instance Properties
    
    @IBOutlet weak var errorLabel: UILabel!
    @IBOutlet weak var errorView: UIView!
    @IBOutlet weak var emailTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!
    
    //MARK: -
    
    var interactor: LoginBusinessLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?
    
    //MARK: - Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
    //MARK: - Setup

    private func setup() {
        let viewController = self
        let interactor = LoginInteractor()
        let presenter = LoginPresenter()
        let router = LoginRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
    // MARK: - Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
          let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
          if let router = router, router.responds(to: selector) {
            router.perform(selector, with: segue)
          }
        }
    }
    
    //MARK: - Instance Methods
    
    @IBAction func onSignInButtonClick(_ sender: UIButton) {
        let request = Login.SignIn.Request(email: self.emailTextField.text!, password: self.passwordTextField.text!)
        self.interactor?.signIn(with: request)
    }
    
    //MARK: -
    
    private func configureDesign() {
        self.emailTextField.attributedPlaceholder = NSAttributedString(string: "Ваша почта КФУ", attributes: Common.Autorization.placeholderAttributes)
        self.passwordTextField.attributedPlaceholder = NSAttributedString(string: "Ваш пароль", attributes: Common.Autorization.placeholderAttributes)
        
        self.navigationController?.navigationBar.titleTextAttributes = [
            .foregroundColor: Constants.titleColor,
            .font: UIFont(name: "HelveticaNeue-Light", size: 17)!
        ]
        self.navigationController?.transparent()
        
        self.emailTextField.addTarget(self, action: #selector(textFieldDidChange(_:)), for: .editingChanged)
        self.passwordTextField.addTarget(self, action: #selector(textFieldDidChange(_:)), for: .editingChanged)
    }
    
    @objc private func textFieldDidChange(_ textField: UITextField) {
        self.emailTextField.textColor = UIColor.white
        self.passwordTextField.textColor = UIColor.white
    }
  
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.configureDesign()
    }
    
    //MARK: - LoginDisplayLogic
    
    func openCoursesScreen() {
        
    }
    
    func showError(with viewModel: Login.SignIn.ViewModel) {
        self.errorView.isHidden = false
        self.errorLabel.text = viewModel.errorMessage
        self.emailTextField.textColor = Common.Autorization.errorColor
        self.passwordTextField.textColor = Common.Autorization.errorColor
    }
    
}
