//
//  AccountSettingsPresenter.swift
//  ITISService
//
//  Created by Timur Shafigullin on 10/12/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountSettingsPresentationLogic {
    func displayInitialAccountSettingsRows()
}

class AccountSettingsPresenter: AccountSettingsPresentationLogic {
    
    weak var viewController: AccountSettingsDisplayLogic!

    func displayInitialAccountSettingsRows() {
        let oldPasswordRow = AccountSettings.TableView.TextFieldModel(title: "Старый пароль", placeholder: "Введите старый пароль")
        
        let newPasswordRow = AccountSettings.TableView.TextFieldModel(title: "Новый пароль", placeholder: "Введите новый пароль")
        
        let confirmNewPasswordRow = AccountSettings.TableView.TextFieldModel(title: "Подтверждение пароля", placeholder: "Введите пароль еще раз")
        
        let passwordSection = DefaultTableViewSection(items: [oldPasswordRow, newPasswordRow, confirmNewPasswordRow], headerTitle: "Пароль")
        
        self.viewController.displayRows(with: [passwordSection])
    }
}
