//
//  AccountSettingsModels.swift
//  ITISService
//
//  Created by Timur Shafigullin on 10/12/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AccountSettings {
    
    // MARK: - Use Cases
  
    enum DoneButton {
        struct Request {
            
        }
        struct Response {
            let hasEmptyField: Bool
        }
        struct ViewModel {
            let doneButtonEnabled: Bool
        }
    }
    
    enum ChangePassword {
        struct Request {
            let oldPassword: String
            let newPassword: String
            let confirmNewPassword: String
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    
    enum TableView {
        struct TextFieldModel: TableViewCompatible {
            
            let title: String
            let placeholder: String?
            
            var onTextFieldDidChange: ((UITextField) -> ())?
            
            var reuseIdentifier: String {
                return TextFieldTableViewCell.identifier()
            }
            
            func cell(for tableView: UITableView, at indexPath: IndexPath) -> UITableViewCell {
                let cell = tableView.dequeueReusableCell(withIdentifier: reuseIdentifier, for: indexPath) as! TextFieldTableViewCell
                
                cell.configure(with: self)
                return cell
            }
        }
    }
}
