//
//  QuestionRouter.swift
//  ITISService
//
//  Created by Тимур Шафигуллин on 27/10/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol QuestionRoutingLogic {
    func showNextQuestionScreen()
}

protocol QuestionDataPassing {
    var dataStore: QuestionDataStore? { get }
}

class QuestionRouter: NSObject, QuestionRoutingLogic, QuestionDataPassing {
    
    weak var viewController: QuestionViewController!
    var dataStore: QuestionDataStore?
    
    func showNextQuestionScreen() {
        let storyboard = UIStoryboard(name: "Quiz", bundle: Bundle.main)
        let questionViewController = storyboard.instantiateViewController(withIdentifier: "questionViewController")
        viewController.navigationController?.pushViewController(questionViewController, animated: true)
    }
    
}
