//
//  SettingsModels.swift
//  ITISService
//
//  Created by Timur Shafigullin on 05/12/2018.
//  Copyright (c) 2018 Timur Shafigullin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Settings {
    
    // MARK: - Use cases
  
    enum InitialState {
        struct Request {
            
        }
        struct Response {
            let settingsNames: [String]
        }
        struct ViewModel {
            
        }
    }
    
    enum UserProfile {
        struct Request {
            
        }
        struct Response {
            let user: User
        }
        struct ViewModel {
            let name: String
            let email: String
            let group: String
            let courseNumber: String
        }
    }
    
    enum SelectCell {
        struct Request {
            let indexPath: IndexPath
        }
        struct Response {
            
        }
        struct ViewModel {
            let title: String
            let confirmTitle: String
            let cancelTitle: String
        }
    }
    
    // MARK: - UITableView Models
    
    enum TableView {
        
        struct Model: TableViewCompatible {
            
            var reuseIdentifier: String {
                return SettingTableViewCell.identifier()
            }
            
            let settingName: String
            
            func cell(for tableView: UITableView, at indexPath: IndexPath) -> UITableViewCell {
                let cell = tableView.dequeueReusableCell(withIdentifier: reuseIdentifier, for: indexPath) as! SettingTableViewCell
                
                cell.configure(with: self)
                
                return cell
            }
        }
        
        struct ExitModel: TableViewCompatible {
            
            var reuseIdentifier: String {
                return ExitTableViewCell.identifier()
            }
            
            func cell(for tableView: UITableView, at indexPath: IndexPath) -> UITableViewCell {
                let cell = tableView.dequeueReusableCell(withIdentifier: reuseIdentifier, for: indexPath)
                return cell
            }
        }
    }
}
